# Generated by Django 6.0.2 on 2026-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
