# Generated by Django 6.0.2 on 2026-02-21 18:59

import django.utils.timezone
from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["-pk"],
                "verbose_name": "planned production",
                "verbose_name_plural": "Production Planning",
            },
        ),
        migrations.AddField(
            model_name="production",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="production",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
