# Generated by Django 6.0.2 on 2026-02-21 19:36

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_production_options_production_created_at_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="production",
            name="quantity_received",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
