# Generated by Django 6.0.2 on 2026-02-21 19:36

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_production_options_production_created_at_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="production",
            name="quantity_received",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
