# Generated by Django 6.0.2 on 2026-03-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_billofmaterials_production__product_4e703f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-closed', '-pk'], 'verbose_name': 'planned production', 'verbose_name_plural': 'Production Planning'},
        ),
    ]
