# Generated by Django 6.0.2 on 2026-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_alter_production_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
