# Generated by Django 6.0.3 on 2026-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_production_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="production_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional per-unit cost for labour, overhead, etc.",
                max_digits=10,
            ),
        ),
    ]
