# Generated by Django 6.0.3 on 2026-03-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_inventoryadjust_created_by_and_more"),
        ("production", "0008_production_created_by_production_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.BigIntegerField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("transaction_id", models.PositiveBigIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_ledger",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Production Ledger",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="production__product_ba4b08_idx"
                    ),
                    models.Index(fields=["date"], name="production__date_79dbef_idx"),
                ],
            },
        ),
    ]
