# Generated by Django 6.0.3 on 2026-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_inventoryledger_action"),
        ("production", "0009_productionledger"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productionledger",
            index=models.Index(
                fields=["transaction_id"], name="production__transac_e67c36_idx"
            ),
        ),
    ]
