# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_add_transaction_id_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['product'], 'permissions': [('manage_bom', 'Can create, edit, and delete bills of materials'), ('manage_production', 'Can create and manage production jobs')], 'verbose_name_plural': 'Bill of Materials Configuration'},
        ),
        migrations.AddField(
            model_name='production',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
