# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_add_transaction_id_index'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['product'], 'permissions': [('manage_bom', 'Can create, edit, and delete bills of materials'), ('manage_production', 'Can create and manage production jobs')], 'verbose_name_plural': 'Bill of Materials Configuration'},
        ),
        migrations.AddField(
            model_name='production',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
