# Generated by Django 6.0.2 on 2026-02-20 15:11

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.RemoveField(
            model_name="inventoryadjust",
            name="closed",
        ),
        migrations.AlterField(
            model_name="inventoryadjust",
            name="complete",
            field=models.BooleanField(default=True),
        ),
    ]
