# Generated by Django 6.0.2 on 2026-02-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryadjust",
            name="closed",
        ),
        migrations.AlterField(
            model_name="inventoryadjust",
            name="complete",
            field=models.BooleanField(default=True),
        ),
    ]
