# Generated by Django 6.0.2 on 2026-02-20 15:11

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.RemoveField(
            model_name="inventoryadjust",
            name="closed",
        ),
        migrations.AlterField(
            model_name="inventoryadjust",
            name="complete",
            field=models.BooleanField(default=True),
        ),
    ]
