# Generated by Django 6.0.2 on 2026-02-21 18:22

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_inventoryadjust_closed_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="inventory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
