# Generated by Django 6.0.2 on 2026-02-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventory_last_updated"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product"], name="inventory_i_product_f4f8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["last_updated"], name="inventory_i_last_up_2d9b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryadjust",
            index=models.Index(
                fields=["product"], name="inventory_i_product_b73769_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryadjust",
            index=models.Index(
                fields=["complete"], name="inventory_i_complet_ecb396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryledger",
            index=models.Index(
                fields=["product", "date"], name="inventory_i_product_aa5085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryledger",
            index=models.Index(
                fields=["transaction_id"], name="inventory_i_transac_cf2cfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionallocated",
            index=models.Index(
                fields=["product"], name="inventory_p_product_9132a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionallocated",
            index=models.Index(
                fields=["quantity"], name="inventory_p_quantit_b1edb0_idx"
            ),
        ),
    ]
