# Generated by Django 6.0.2 on 2026-02-21 23:09

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventory_inventory_i_product_f4f8f8_idx_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="inventory",
            name="required_cached",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
