# Generated by Django 6.0.2 on 2026-03-07 10:04

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventory_required_cached"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
