# Generated by Django 6.0.3 on 2026-03-08 18:11

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_product_sale_price"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="product",
            name="catalogue_item",
            field=models.BooleanField(
                default=False,
                help_text="List this product in the catalogue. Requires a sale price.",
            ),
        ),
    ]
