# Generated by Django 6.0.3 on 2026-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_product_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catalogue_item",
            field=models.BooleanField(
                default=False,
                help_text="List this product in the catalogue. Requires a sale price.",
            ),
        ),
    ]
