# Generated by Django 6.0.3 on 2026-03-09 17:59

import django.db.models.deletion
from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_add_catalogue_item_to_product"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterField(
            model_name="stocktransfer",
            name="from_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_out",
                to="inventory.location",
            ),
        ),
    ]
