# Generated by Django 6.0.3 on 2026-03-09 18:01

import django.db.models.deletion
from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_allow_transfer_from_unallocated"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_in",
                to="inventory.location",
            ),
        ),
    ]
