# Generated by Django 6.0.3 on 2026-03-10 20:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_allow_transfer_to_unallocated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventorylocation",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["inventory"], name="inventory_s_invento_fe5924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["transferred_at"], name="inventory_s_transfe_9ccf0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["from_location"], name="inventory_s_from_lo_41b1d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["to_location"], name="inventory_s_to_loca_c0003b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorylocation",
            constraint=models.UniqueConstraint(
                fields=("inventory", "location"), name="unique_inventory_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="product_name_ci_unique",
            ),
        ),
    ]
