# Generated by Django 6.0.3 on 2026-03-11 13:20

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_inventorylocation_unique_together_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Barcode or QR code value for scanning.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Stock Keeping Unit identifier.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
