# Generated by Django 6.0.3 on 2026-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_inventoryadjust_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryledger",
            name="action",
            field=models.CharField(
                choices=[
                    ("Purchase Order", "Purchase Order"),
                    ("Sales Order", "Sales Order"),
                    ("Production", "Production"),
                    ("Inventory Adjustment", "Inventory Adjustment"),
                    ("Stock Transfer", "Stock Transfer"),
                    ("Seed", "Seed"),
                ],
                max_length=128,
            ),
        ),
    ]
