# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventoryledger_action'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('manage_products', 'Can create, edit, and delete products'), ('manage_stock', 'Can adjust stock and transfer inventory'), ('manage_locations', 'Can create, edit, and delete locations')], 'verbose_name_plural': 'Inventory Management'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
