# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventoryledger_action'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('manage_products', 'Can create, edit, and delete products'), ('manage_stock', 'Can adjust stock and transfer inventory'), ('manage_locations', 'Can create, edit, and delete locations')], 'verbose_name_plural': 'Inventory Management'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
