# Generated by Django 6.0.2 on 2026-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Address line 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Address line 2"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=128)),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="State / Region"
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=128)),
                ("name", models.CharField(max_length=256)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("email", models.CharField(blank=True, max_length=128)),
                ("website", models.CharField(blank=True, max_length=256)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("vat_number", models.CharField(blank=True, max_length=64)),
                ("company_number", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "Company Configuration",
            },
        ),
    ]
