# Generated by Django 6.0.2 on 2026-03-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairedInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(
                        help_text="Base URL of the remote instance, e.g. https://acme.example.com"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="The key they gave us to authenticate our requests",
                        max_length=64,
                    ),
                ),
                (
                    "our_key",
                    models.CharField(
                        blank=True,
                        help_text="The key we generated for them to call us",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
