# Generated by Django 6.0.2 on 2026-03-08 17:12

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_pairedinstance"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterField(
            model_name="pairedinstance",
            name="api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The key they gave us to authenticate our requests",
                max_length=64,
            ),
        ),
    ]
