# Generated by Django 6.0.2 on 2026-03-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_pairedinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pairedinstance",
            name="api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The key they gave us to authenticate our requests",
                max_length=64,
            ),
        ),
    ]
