# Generated by Django 6.0.3 on 2026-03-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_alter_pairedinstance_api_key"),
        ("procurement", "0008_alter_supplierproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairedinstance",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paired_instances",
                to="procurement.supplier",
            ),
        ),
    ]
