# Generated by Django 6.0.3 on 2026-03-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_add_supplier_to_paired_instance"),
        ("sales", "0006_remove_customer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairedinstance",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paired_instances",
                to="sales.customer",
            ),
        ),
    ]
