# Generated by Django 6.0.3 on 2026-03-13 15:25

import django.db.models.deletion
from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    migration_setting = IgnoreMigration()

    dependencies = [
        ("config", "0006_notification_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(
                        help_text="The URL that will receive POST requests."
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Shared secret for HMAC-SHA256 signature verification.",
                        max_length=128,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of event types this endpoint subscribes to.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="config.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Webhook deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "-created_at"],
                        name="config_webh_endpoin_5c7a9f_idx",
                    )
                ],
            },
        ),
    ]
