# Generated by Django 6.0.3 on 2026-03-13 19:29

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_webhook_models'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name='companyconfig',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Send email copies of low-stock alerts and overdue order warnings.'),
        ),
    ]
