# Generated by Django 6.0.3 on 2026-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_webhook_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Send email copies of low-stock alerts and overdue order warnings.'),
        ),
    ]
