# Generated by Django 6.0.3 on 2026-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('order_overdue', 'Order Overdue'), ('order_status', 'Order Status Change'), ('price_update', 'Price Update')], max_length=32),
        ),
    ]
