# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_add_price_update_notification_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfig',
            options={'permissions': [('manage_company', 'Can manage company configuration'), ('manage_pairing', 'Can manage paired instances'), ('manage_webhooks', 'Can manage webhook endpoints')], 'verbose_name': 'Company Configuration'},
        ),
    ]
