# Generated by Django 6.0.2 on 2026-02-20 12:54

import django.db.models.deletion
from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterField(
            model_name="purchaseledger",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_ledgers",
                to="procurement.supplier",
            ),
        ),
    ]
