# Generated by Django 6.0.2 on 2026-02-21 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_inventoryadjust_closed_and_more"),
        ("procurement", "0002_alter_purchaseledger_supplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierproduct",
            options={},
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="supplierproduct",
            unique_together={("supplier", "product")},
        ),
    ]
