# Generated by Django 6.0.2 on 2026-02-21 13:36

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_alter_supplierproduct_options_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="purchaseorderline",
            name="quantity_received",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
