# Generated by Django 6.0.2 on 2026-03-01 17:13

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0006_purchaseorder_total_amount_cached"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.RemoveField(
            model_name="supplier",
            name="address",
        ),
        migrations.RemoveField(
            model_name="suppliercontact",
            name="address",
        ),
        migrations.AddField(
            model_name="supplier",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Address line 1"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Address line 2"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="supplier",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="supplier",
            name="state",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="State / Region"
            ),
        ),
        migrations.AddField(
            model_name="suppliercontact",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Address line 1"
            ),
        ),
        migrations.AddField(
            model_name="suppliercontact",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Address line 2"
            ),
        ),
        migrations.AddField(
            model_name="suppliercontact",
            name="city",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="suppliercontact",
            name="country",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="suppliercontact",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="suppliercontact",
            name="state",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="State / Region"
            ),
        ),
    ]
