# Generated by Django 6.0.2 on 2026-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventory_required_cached"),
        ("procurement", "0007_remove_supplier_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierproduct",
            options={"ordering": ["product__name"]},
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["supplier"], name="procurement_supplie_8d5f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["product"], name="procurement_product_d1388b_idx"
            ),
        ),
    ]
