# Generated by Django 6.0.3 on 2026-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_alter_supplierproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
