# Generated by Django 6.0.3 on 2026-03-10 20:39

import django.db.models.functions.text
from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_inventorylocation_unique_together_and_more"),
        ("procurement", "0009_add_due_date_to_purchase_order"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterUniqueTogether(
            name="supplierproduct",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["due_date"], name="procurement_due_dat_5af155_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="supplier_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.UniqueConstraint(
                fields=("supplier", "product"), name="unique_supplier_product"
            ),
        ),
    ]
