# Generated by Django 6.0.3 on 2026-03-11 15:54

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_purchaseorder_created_by_purchaseorder_updated_by"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="purchaseorderline",
            name="store_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="store_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
