# Generated by Django 6.0.3 on 2026-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_inventoryledger_action"),
        ("procurement", "0012_store_confirmed_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchaseledger",
            index=models.Index(
                fields=["transaction_id"], name="procurement_transac_0ffe91_idx"
            ),
        ),
    ]
