# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_po_templates'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('manage_suppliers', 'Can create, edit, and delete suppliers'), ('manage_purchase_orders', 'Can create, receive, and close purchase orders')], 'verbose_name_plural': 'Supplier Management'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
