# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_po_templates'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('manage_suppliers', 'Can create, edit, and delete suppliers'), ('manage_purchase_orders', 'Can create, receive, and close purchase orders')], 'verbose_name_plural': 'Supplier Management'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
