# Generated by Django 6.0.2 on 2026-02-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventory_inventory_i_product_f4f8f8_idx_and_more"),
        ("sales", "0003_salesorder_created_at_salesorder_updated_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customerproduct",
            index=models.Index(
                fields=["customer"], name="sales_custo_custome_b24944_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerproduct",
            index=models.Index(
                fields=["product"], name="sales_custo_product_d5ed59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesledger",
            index=models.Index(
                fields=["product", "customer"], name="sales_sales_product_243ebb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesledger",
            index=models.Index(fields=["date"], name="sales_sales_date_66558b_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer"], name="sales_sales_custome_b24b56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["created_at"], name="sales_sales_created_f48ee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(
                fields=["sales_order", "complete"],
                name="sales_sales_sales_o_fd0783_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(
                fields=["product"], name="sales_sales_product_b4378b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(fields=["closed"], name="sales_sales_closed_db7c1f_idx"),
        ),
    ]
