# Generated by Django 6.0.3 on 2026-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_remove_customer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="ship_by_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
