# Generated by Django 6.0.3 on 2026-03-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_allow_transfer_to_unallocated"),
        ("sales", "0007_add_ship_by_date_to_sales_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick_lists",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pick Lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickListLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pick_list_lines",
                        to="inventory.location",
                    ),
                ),
                (
                    "pick_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.picklist",
                    ),
                ),
                (
                    "sales_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick_list_lines",
                        to="sales.salesorderline",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pick List Lines",
                "ordering": ["sales_order_line", "location"],
            },
        ),
    ]
