# Generated by Django 6.0.3 on 2026-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_picklist_picklistline"),
    ]

    operations = [
        migrations.AddField(
            model_name="picklistline",
            name="is_shortage",
            field=models.BooleanField(default=False),
        ),
    ]
