# Generated by Django 6.0.3 on 2026-03-09 19:16

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_picklist_picklistline"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="picklistline",
            name="is_shortage",
            field=models.BooleanField(default=False),
        ),
    ]
