# Generated by Django 6.0.3 on 2026-03-10 20:39

import django.db.models.functions.text
from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation as IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_pick_list_line_is_shortage"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["ship_by_date"], name="sales_sales_ship_by_db3663_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="customer_name_ci_unique",
            ),
        ),
    ]
