# Generated by Django 6.0.3 on 2026-03-11 13:21

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def database_backwards(self, app_label, schema_editor, from_state, to_state):
            pass

        def describe(self):
            return "IgnoreMigration (no-op)"


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_salesorder_sales_sales_ship_by_db3663_idx_and_more"),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AddField(
            model_name="picklistline",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="picklistline",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
