# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesorder_created_by_salesorder_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('manage_customers', 'Can create, edit, and delete customers'), ('manage_sales_orders', 'Can create, ship, and close sales orders')], 'verbose_name_plural': 'Customer Management'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
