# Generated by Django 6.0.3 on 2026-03-15 15:07

from django.db import migrations, models

try:
    from django_migration_linter import IgnoreMigration
except ImportError:
    from django.db.migrations.operations.base import Operation

    class IgnoreMigration(Operation):
        def state_forwards(self, app_label, state):
            pass

        def database_forwards(self, app_label, schema_editor, from_state, to_state):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesorder_created_by_salesorder_updated_by'),
    ]

    operations = [
        IgnoreMigration(),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('manage_customers', 'Can create, edit, and delete customers'), ('manage_sales_orders', 'Can create, ship, and close sales orders')], 'verbose_name_plural': 'Customer Management'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
